# Generated by Django 4.2 on 2024-01-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('dex_num', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('hp', models.SmallIntegerField()),
                ('attack', models.SmallIntegerField()),
                ('sp_atk', models.SmallIntegerField()),
                ('defense', models.SmallIntegerField()),
                ('sp_def', models.SmallIntegerField()),
                ('speed', models.SmallIntegerField()),
                ('ability', models.CharField(max_length=50)),
                ('type', models.ManyToManyField(to='pokemon.type')),
            ],
        ),
    ]
