# Generated by Django 4.2 on 2024-01-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='sp_atk',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='sp_def',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
