# Generated by Django 4.2 on 2024-01-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_remove_pokemon_attack_remove_pokemon_defense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='dex_num',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
