# Generated by Django 4.2 on 2024-01-17 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('permissions_updated_at', models.DateTimeField()),
                ('guid_password_reset', models.UUIDField(blank=True, null=True, unique=True)),
                ('guid_password_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
