# Generated by Django 4.2 on 2024-01-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('preferred_type', models.CharField(max_length=50)),
                ('badge_name', models.CharField(max_length=100)),
                ('team', models.JSONField()),
            ],
        ),
    ]
